
language: go

go:
  - "1.10"

install: true
notifications:
  email: false

jobs:
  include:
    - stage: Test
      script:
      - go get -v -d ./...
      - go get github.com/stretchr/testify/assert
      - go get github.com/bouk/monkey
      - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
      - bash <(curl -s https://codecov.io/bash)